[theme]
primaryColor = "#1E2250"                # Amarelo - similar ao botão
backgroundColor = "#ffffff"             # AMarelo claro para o fundo
secondaryBackgroundColor = "#f5f5f5"    # Azul claro para o fundo dos widgets
textColor = "#2d377a"                   # Azul - similar aom texto do MercadoLivre
font = "sans serif"                     # Fonte